###########################################
# Fichero de configuracion
###########################################
MACHINE := $(shell uname -m)

ifeq ($(MACHINE), x86_64)
libdir=lib64
endif
ifeq ($(MACHINE), i686)
libdir=lib
endif

LOG             = yes
DEBUG           = yes
FLASHSTREAMER   = no
ADDLIBPATH      = ../staticdeps
MEDKITDIR       = ../third_party/fontventa/libmedikit
# libbfcp est desormais un sous-module bati in-tree (comme libmedkit) : en-tetes
# et archive pris dans l'arbre du sous-module, plus de dependance a /opt/ives.
BFCPDIR         = ../third_party/libbfcp
BFCPINCLUDE     = $(BFCPDIR)/include
# libmedkit (sous-module) est desormais la source unique des codecs : liaison
# inconditionnelle de libmedkit.a. Le mode sans-medkit a ete supprime (les .o de
# codecs repris par medkit ont ete retires de OBJS). Voir integration_libmedkit.md.
VADWEBRTC       = yes
PROTOC		= ../staticdeps/bin/protoc
DISTRO          = $(shell head -1 /etc/redhat-release | awk \
                      '{if ($$0 ~ /Fedora/) {print "fc"} else if ($$0 ~ /CentOS release 5/) {print "el5"} else if ($$0 ~ /CentOS release 6/) {print "el6"}}' )
#DEBUG
#OPTS=-msse -msse2 -msse3 -D__SSE2__  
OPTS=-std=gnu++17 -Werror=return-type -Werror=delete-non-virtual-dtor -Werror=int-to-pointer-cast

ifeq ($(FEWSTATICDEPS),yes)
    OPTS+= -DFEWSTATICDEPS -I/usr/include/ffmpeg
endif

ifeq ($(GPROF),yes)
        OPTS+= -g -O0 -pg
        LDFLAGS +=  -pg
endif

ifeq ($(DEBUG),yes)
	TAG=debug
	OPTS+= -g -O0
	BFCPLIBS=$(BFCPDIR)/lib/libbfcpdbg.a
else
	OPTS+= -O3
	TAG=release
	BFCPLIBS=$(BFCPDIR)/lib/libbfcprel.a
endif

#LOG
ifeq ($(LOG),yes)
	OPTS+= -DLOG_
endif

############################################
#Directorios
############################################
BUILD = media/build/$(TAG)
BIN   = ../bin/$(TAG)

############################################
#Objetos
############################################
# G711 fourni par libmedkit (PCMUEncoder/PCMAEncoder, FfAudioEncoder). Repertoire mcu supprime.
# H263/H263+/MPEG4 entierement fournis par libmedkit (FfVideoDecoder/FfVideoEncoder). Repertoire mcu supprime.

JSR309DIR=jsr309
JSR309OBJ=JSR309Event.o WSEndpoint.o RTPEndpoint.o Player.o Endpoint.o  MediaSession.o \
    JSR309Manager.o RTPMultiplexer.o xmlrpcjsr309.o AudioDecoderWorker.o \
    AudioEncoderWorker.o AudioMixerResource.o VideoDecoderWorker.o VideoEncoderWorker.o \
    VideoMixerResource.o RTPMultiplexerSmoother.o Recorder.o AudioTranscoder.o Joinable.o


# H264 entierement fourni par libmedkit (encoder, decoder, depacketizer). Repertoire mcu supprime.

# Speex fourni par libmedkit (FfAudioEncoder/Decoder, ffmpeg AV_CODEC_ID_SPEEX). Repertoire mcu supprime.


DOCSHARINGOBJ= stunmessage.o crc32calc.o remoteratecontrol.o uploadhandler.o http.o appmixer.o

MOTELIDIR=moteli
MOTELIOBJ=rabbitmqmcu.o mcu.pb.o rabbitmqserver.o

OBJS=httpparser.o websocketserver.o websocketconnection.o websockettransport.o mcu.o multiconf.o rtpparticipant.o rtmpparticipant.o videomixer.o audiomixer.o xmlrpcserver.o xmlhandler.o xmlstreaminghandler.o statushandler.o xmlrpcmcu.o rtpsession.o audiostream.o videostream.o pipeaudioinput.o pipeaudiooutput.o pipevideoinput.o pipevideooutput.o
# logo.o : fourni par libmedkit.a (medkit/logo.h). mcu ne compile plus son propre
# logo.cpp pour eviter la double definition au link (picturestreamer/mp4writer de
# libmedkit tirent la classe Logo de l'archive).
OBJS+=framescaler.o mosaic.o mosaiccompositor.o partedmosaic.o asymmetricmosaic.o pipmosaic.o overlay.o amf.o rtmpmessage.o rtmpchunk.o rtmpstream.o rtmpconnection.o  rtmpserver.o broadcaster.o broadcastsession.o rtmpflvstream.o flvrecorder.o FLVEncoder.o xmlrpcbroadcaster.o mediagateway.o mediabridgesession.o 
OBJS+=xmlrpcmediagateway.o textmixer.o textmixerworker.o textstream.o pipetextinput.o pipetextoutput.o mp4player.o mp4streamer.o audioencoder.o audiodecoder.o textencoder.o mp4recorder.o rtmpmp4stream.o rtmpnetconnection.o rtmpclientconnection.o avcdescriptor.o RTPSmoother.o rtp.o fecdecoder.o sidebar.o \
      vad.o dtls.o VideoTranscoder.o remoterateestimator.o eventstreaminghandler.o videopipe.o videorescaler.o redcodec.o shareddocmixer.o mcustatushandler.o dtmfmessage.o

OBJS+= $(DOCSHARINGOBJ) $(JSR309OBJ)
TARGETS=mcu rtmptest mediagw

OBJS2=mcu.o multiconf.o rtpparticipant.o rtmpparticipant.o videomixer.o audiomixer.o xmlrpcserver.o xmlhandler.o xmlstreaminghandler.o statushandler.o xmlrpcmcu.o rtpsession.o audiostream.o videostream.o pipeaudioinput.o pipeaudiooutput.o pipevideoinput.o pipevideooutput.o 
OBJS2+=framescaler.o overlay.o amf.o rtmpmessage.o rtmpchunk.o rtmpstream.o rtmpconnection.o  rtmpserver.o broadcaster.o broadcastsession.o rtmpflvstream.o flvrecorder.omediagateway.o mediabridgesession.o mcustatushandler.o
OBJS2+=xmlrpcmediagateway.o textstream.o pipetextinput.o pipetextoutput.o audioencoder.o audiodecoder.o textencoder.o rtmpnetconnection.o rtmpclientconnection.o avcdescriptor.o RTPSmoother.o rtp.o fecdecoder.o vad.o 
OBJS2+=remoterateestimator.o eventstreaminghandler.o VideoTranscoder.o videopipe.o videorescaler.o redcodec.o
OBJS2+= $(JSR309OBJ) $(DOCSHARINGOBJ)

ifeq ($(FLASHSTREAMER),yes)
	OBJS+= flash.o xmlrpcflash.o 
	OBJSFS   = flashstreamer.o FlashPlayer.o FlashSoundHandler.o $(OBJS)
	OBJSFSCLIENT = xmlrpcclient.o xmlrpcflashclient.o
	TARGETS += flashstreamer flashclient testflash
endif

ifeq ($(VADWEBRTC),yes)
        # VAD via le paquet systeme webrtc-audio-processing (module APM).
        VADINCLUDE = $(shell pkg-config --cflags webrtc-audio-processing)
        VADLD = $(shell pkg-config --libs webrtc-audio-processing)
        OPTS+= -DVADWEBRTC
else
        VADINCLUDE =
        VADLD =
endif

ifeq ($(MOTELI),yes)
	OPTS+= -DMOTELI=yes
	OBJS+= $(MOTELIOBJ)
	LDFLAGS += -Wl,-Bstatic -lamqpcpp -lrabbitmq -lprotobuf -Wl,-Bdynamic
endif

OBJSMCU = $(OBJS) main.o
OBJSRTMPTEST = $(OBJS) rtmptest.o
OBJSWSTEST = $(OBJS) wstest.o

BUILDOBJSMCU = $(addprefix $(BUILD)/,$(OBJSMCU))
BUILDOBJSRTMPTEST= $(addprefix $(BUILD)/,$(OBJSRTMPTEST))
BUILDOBJSWSTEST= $(addprefix $(BUILD)/,$(OBJSWSTEST))
BUILDOBJSMEDIAGW= $(addprefix $(BUILD)/,$(OBJS2))
BUILDOBJSFS= $(addprefix $(BUILD)/,$(OBJSFS)) 
BUILDOBJSFSCLIENT= $(addprefix $(BUILD)/,$(OBJSFSCLIENT))

###################################
#Compilacion condicional
###################################
VPATH  =  %.o $(BUILD)/
VPATH +=  %.c src/
VPATH +=  %.cpp src/
VPATH +=  %.cpp src/$(JSR309DIR)

ifeq ($(MOTELI),yes)
    VPATH +=  %.cpp src/$(MOTELIDIR)
    VPATH +=  %.cc src/$(MOTELIDIR)
    VPATH +=  %.proto src/$(MOTELIDIR)
endif

# ImageMagick : Magick++ 7 (AlmaLinux 9) via pkg-config. Fournit le bon -I
# (ImageMagick-7), les -DMAGICKCORE_* requis et les libs Magick++-7.Q16HDRI.
MAGICKCFLAGS    := $(shell pkg-config --cflags Magick++)
MAGICKLIBS      := $(shell pkg-config --libs Magick++)

INCLUDE+= -Iinclude/ -I$(ADDLIBPATH)/include $(VADINCLUDE) $(MAGICKCFLAGS) -I$(BFCPINCLUDE) -I/usr/include/ffmpeg

# libmedikit est desormais OBLIGATOIRE (plus de mode sans-medkit) : les codecs
# proviennent du sous-module. En-tetes (medkit/, astmedkit/) et archive pris
# dans l'arbre du sous-module, sans install dans /opt/ives. -I$(MEDKITDIR) place
# AVANT -Iinclude/ pour que les en-tetes du sous-module priment (et que les
# inclusions <g722/...>/<amr/...> visent le codec medkit, pas l'homonyme mcu/src).
INCLUDE := -I$(MEDKITDIR) $(INCLUDE)
MEDKITLIB = $(MEDKITDIR)/libmedkit.a

LDFLAGS+= $(BFCPLIBS) -L$(ADDLIBPATH)/lib 
LDFLAGS+= $(MEDKITLIB)

ifeq ($(MOTELI),yes)
	LDFLAGS += -lamqpcpp -lrabbitmq -lprotobuf 
endif

ifeq ($(FEWSTATICDEPS),yes)
    # Use of dynamic libs (on FC20 ...)
    LDFLAGS += -Wl,-Bstatic -lssl -lcrypto -lfdk-aac -lx264 -lvpx -lg722_1 -lspeex -Wl,-Bdynamic -lsrtp2 -lavcodec -lswscale -lavfilter -lswresample -lavformat -lavutil -lavdevice -lpostproc -lmp4v2 -lpthread $(MAGICKLIBS) -lbz2 -lopencore-amrnb -lopencore-amrwb
	LDXMLFLAGS+= -lxmlrpc_abyss -lxmlrpc_server -lxmlrpc -lxmlrpc_util
else
    # Usin static libs (CentOS)
ifeq ($(DISTRO), el5)   
	LDFLAGS += -Wl,-Bstatic -lmp4v2 -lavcodec -lswscale -lavfilter -lswresample -lavformat -lavutil -lavdevice -lpostproc -lfdk-aac -lx264 -lvpx -lg722_1 -lspeex -Wl,-Bdynamic -lsrtp2 -lmp4v2 $(MAGICKLIBS) -lbz2 -lopencore-amrnb -lopencore-amrwb
else 
	# AMR-NB/WB : fournis par libmedkit via libavcodec (encodeurs libopencore_amrnb
	# / libvo_amrwbenc lies dynamiquement dans libavcodec.so). Plus de -lopencore-amr*.
	# x264 : plus de lien direct ; l'encodeur H264 de libmedkit passe par
	# libavcodec (h264_vaapi si dispo, libx264 en repli).
	LDFLAGS += -lsrtp2 -lavcodec -lswscale -lavfilter -lswresample -lavformat -lavutil -lavdevice -lpostproc -lmp4v2 $(MAGICKLIBS) -lbz2 -ldl -lz
endif
	# OpenSSL : libs dynamiques du systeme (AlmaLinux 9) au lieu des .a statiques
	# (plus de build openssl dans staticdeps).
	# XML : xmlrpc-c est bati avec le backend libxml2 ; xmlParseChunk vient donc de
	# la libxml2 systeme (-lxml2), pas des archives expat libxmlrpc_xmlparse/xmltok
	# (non produites dans ce mode).
	# xmlrpc-c : paquet systeme (xmlrpc-c-devel, depot crb) lie dynamiquement,
	# plus de build source dans staticdeps. Backend libxml2 (idem qu'avant).
	LDXMLFLAGS+=  -lxmlrpc_abyss -lxmlrpc_server -lxmlrpc -lxmlrpc_util -lxml2 -lssl -lcrypto -lpthread
endif
    

LDFLAGS+= $(LDXMLFLAGS)

#For abyss
OPTS 	+= -D_UNIX -D__STDC_CONSTANT_MACROS -fPIC

CFLAGS  += $(INCLUDE) $(OPTS)
CXXFLAGS+= $(INCLUDE) $(OPTS)

mcu.pb.cc: mcu.proto
	$(PROTOC) --cpp_out=$(PWD) src/moteli/mcu.proto

rabbitmqmcu.o: rabbitmqmcu.cpp rabbitmqmcu.h mcu.pb.cc
	$(CXX) $(CXXFLAGS) -c $< -o $(BUILD)/$@

mcu.pb.o: mcu.pb.cc
	$(CXX) $(CXXFLAGS) -I$(PWD) -c $< -o $(BUILD)/$@

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $(BUILD)/$@

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $(BUILD)/$@

############################################
#Targets
############################################
all: mkdirs $(TARGETS) 

mkdirs:  
	mkdir -p $(BUILD)
	mkdir -p $(BIN)
clean:
	rm -f $(BUILDOBJSMCU)
	rm -f $(BUILDOBJSFS)
	rm -f "$(BIN)/mcu"
	rm -f "$(BIN)/flashstreamer"

install:
	cp $(BUILD)/mcu $(TARGET)/mediaserver

############################################
#MCU
############################################

mcu: mkdirs $(OBJSMCU)
	$(CXX) -o $(BIN)/$@ $(BUILDOBJSMCU) $(LDFLAGS) $(VADLD)

rtmptest: $(OBJSRTMPTEST)
	$(CXX) -o $(BIN)/$@ $(BUILDOBJSRTMPTEST) $(LDFLAGS)

wstest: mkdirs $(OBJSWSTEST)
	$(CXX) -o $(BIN)/$@ $(BUILDOBJSWSTEST) $(LDFLAGS) $(VADLD)

mediagw:  $(OBJS2) maingw.o
	$(CXX) -o $(BIN)/$@ $(OBJSMEDIAGW) maingw.o $(LDFLAGS)
	
flashstreamer: $(OBJSFS) $(OBJS)
	g++ $(GNASHLD) -o $(BIN)/$@ $(BUILDOBJSFS) $(BUILDOBJS) $(GNASHBASE)/backend/.libs/libgnashagg.a  /usr/lib/libagg.a  $(LDFLAGS)

